// @ts-check

/**
 * Sidebar de la sección "Ingresantes".
 * Se genera automáticamente a partir de los archivos en `ingresantes/`.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  ingresantesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
