// @ts-check

/**
 * Sidebar de la sección "Estudiantes".
 * Se genera automáticamente a partir de los archivos en `estudiantes/`.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  estudiantesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
